
# pcd dir
pcd_dir : "C:\\Users\\maser\\Documents\\GitHub\\SemanticKITTI-visualizer\\BIN Files New"
pcd_extension : ".bin"

# this store the dataset config
dataset_cfg_path : "C:\\Users\\maser\\Documents\\GitHub\\SemanticKITTI-visualizer\\src\\config\\semantic-kitti.yaml"

# this store the viewpoint initialization config, which can copy from open3d GUI (json file) to modify initialization of the viewpoint
viewpoint_cfg_path : "C:\\Users\\maser\\Documents\\GitHub\\SemanticKITTI-visualizer\\src\\config\\viewpoint.json"

# # left top point position of GUI
# position : 
#   left : 300
#   top : 100
#   width : 1400
#   height : 800

# open3d pcd point size
point_size : 2
